services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - API_HOST=http://api:8000
      - NEXT_PUBLIC_API_HOST=http://localhost:8000
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    tty: true
