services:
  frontend:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - API_HOST=http://backend:3001
      - NEXT_PUBLIC_API_HOST=http://localhost:3001
    working_dir: /app
    tty: true