services:
  backend:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile.backend
    volumes:
      - ./src/backend:/app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=sample
      - JWT_EXPIRATION=2592000
      - JWT_SECRET=secret
    working_dir: /app
    tty: true

  frontend:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile.frontend
    volumes:
      - ./src/frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - API_HOST=http://backend:3001
      - NEXT_PUBLIC_API_HOST=http://localhost:3001
    working_dir: /app
    tty: true

  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: sample
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data 