services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    working_dir: /app
    command: sh -c "npm run build && npm run start"
    restart: always
